Add an override for the resource pattern loader.
(Applies @geomacy's work to the layout here, in karaf/ instead of brooklyn-tosca-osgi/)

This is motivated by the problem that the component scanning in Spring isn't finding
resources from our bundles.  We get exceptions like

11:38:39,045 WARN  316 atchingResourcePatternResolver [tp1719091855-872] Cannot search for matching files underneath URL [bundle://316.0:14/org/elasticsearch/mapping/] because it does not correspond to a directory in the file system
java.io.FileNotFoundException: URL [bundle://316.0:14/org/elasticsearch/mapping/] cannot be resolved to absolute file path because it does not reside in the file system: bundle://316.0:14/org/elasticsearch/mapping/
	at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:212)
	at org.springframework.core.io.AbstractFileResolvingResource.getFile(AbstractFileResolvingResource.java:52)
	at org.springframework.core.io.UrlResource.getFile(UrlResource.java:212)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.doFindPathMatchingFileResources(PathMatchingResourcePatternResolver.java:598)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.findPathMatchingResources(PathMatchingResourcePatternResolver.java:419)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.getResources(PathMatchingResourcePatternResolver.java:273)
	at org.springframework.context.support.AbstractApplicationContext.getResources(AbstractApplicationContext.java:1159)
	at org.springframework.context.support.GenericApplicationContext.getResources(GenericApplicationContext.java:223)
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:270)
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:248)
	at org.springframework.context.annotation.ComponentScanAnnotationParser.parse(ComponentScanAnnotationParser.java:140)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:262)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:226)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:193)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:163)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:306)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:239)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:254)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:94)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:606)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:462)
	at io.cloudsoft.tosca.a4c.platform.Alien4CloudSpringContext.newApplicationContext(Alien4CloudSpringContext.java:46)
	at io.cloudsoft.tosca.a4c.brooklyn.plan.ToscaTypePlanTransformer.initialiseAlien(ToscaTypePlanTransformer.java:85)

Now the Spring `AnnotationConfigApplicationContext` class that’s used in
`Alien4CloudSpringContext#newApplicationContext` allows us to set our own resourceLoader
(regular `setResourceLoader` method). If we set one, then that will override the default
`ResourcePatternResolver` that is currently being used to locate resources.

This commit creates our own subclass of `PathMatchingResourcePatternResolver` that overrides
`getResources()` to be aware of the `bundle:` prefix.

That should then allow us to do whatever we wanted to resolve `bundle:` resources,
which should let us fetch resources from OSGI bundles. At the moment it just does some
logging, e.g:

$ tail -f /Users/geoff/workspaces/cloudsoft/amp/amp/karaf/cloudsoft-amp/target/cloudsoft-amp-karaf-4.0.0-SNAPSHOT/log/amp.debug.log | grep 'OSGI lookup'
17:40:44,939 DEBUG 319 atchingResourcePatternResolver [p1775378491-1558] Overriding getResources for OSGI lookup of classpath*:io/cloudsoft/tosca/a4c/platform/**/*.class
17:40:44,939 DEBUG 319 atchingResourcePatternResolver [p1775378491-1558] Overriding getResources for OSGI lookup of classpath*:io/cloudsoft/tosca/a4c/platform/
17:40:44,941 DEBUG 319 atchingResourcePatternResolver [p1775378491-1558] Overriding getResources for OSGI lookup of classpath*:alien4cloud/**/*.class
17:40:44,941 DEBUG 319 atchingResourcePatternResolver [p1775378491-1558] Overriding getResources for OSGI lookup of classpath*:alien4cloud/
17:40:44,941 DEBUG 319 atchingResourcePatternResolver [p1775378491-1558] Overriding getResources for OSGI lookup of classpath*:org/elasticsearch/mapping/**/*.class
17:40:44,941 DEBUG 319 atchingResourcePatternResolver [p1775378491-1558] Overriding getResources for OSGI lookup of classpath*:org/elasticsearch/mapping/
17:40:44,941 DEBUG 319 atchingResourcePatternResolver [p1775378491-1558] Overriding getResources for OSGI lookup of classpath*:io/cloudsoft/tosca/a4c/brooklyn/**/*.class
17:40:44,941 DEBUG 319 atchingResourcePatternResolver [p1775378491-1558] Overriding getResources for OSGI lookup of classpath*:io/cloudsoft/tosca/a4c/brooklyn/